blank_issues_enabled: true
contact_links:
  - name: Have a questiohn?
    url: https://www.ellpeck.de/actaddmanual/
    about: Make sure to read the online manual first!
  - name: Not sure it is a bug?
    url: https://discord.com/invite/Uy2ZM9X
    about: Go check out Ellpeck's Discord if you aren't sure about something.
