name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "microsoft"
          java-version: 21
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Use gradle tasks
        env:
          MR_TOKEN: ${{ secrets.MR_TOKEN }}
          CF_TOKEN: ${{ secrets.CF_TOKEN }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build publish publishMods
